assignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views
app_name='website'


urlpatterns = [
 path('',views.index),
 path('register',views.register,name='register'),
 path('login',views.login,name='login'),
 path('home/<int:id>',views.home,name='home'),
 path('update/<int:id>',views.update,name='update'),
 path('changePass/<int:id>',views.changePass,name='changePass'),
 path('logout',views.logout,name='logout'),
 path('product',views.product,name='product'),
 path('productdetails/<int:id>',views.productdetails,name='productdetails')
 
 ]

website/models.py
from typing import DefaultDict
from django.contrib.admin.sites import DefaultAdminSite
from django.db import models

# Create your models here.
class SignUp(models.Model):
    Name=models.CharField(max_length=10,default='')
    Designation=models.CharField(max_length=20,default='')
    Email=models.EmailField(default='')
    Password=models.CharField(max_length=8,default='')
    Pic=models.ImageField(default='')
    Phone=models.IntegerField(default='')
class ProductTable(models.Model):
    Product_Name=models.CharField(max_length=20,default='')
    Model=models.CharField(max_length=10,default='')
    Price=models.IntegerField(default='')
    color=models.CharField(max_length=10,default='')
    image=models.ImageField(default='')

website/forms.py
from django import forms
from django.forms import fields
from . models import ProductTable,SignUp
class SignUpForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=8)
    ConfirmPassword=forms.CharField(label='Confirm Password',widget=forms.PasswordInput,max_length=8,min_length=8)
    class Meta():
        model=SignUp
        fields='__all__'
class LoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput)
    class Meta():
        model=SignUp
        fields=('Email','Password',)        
class UpdateForm(forms.ModelForm):
    class Meta():
        model=SignUp
        fields=('Name','Designation','Email','Pic','Phone')
class ChangePasswordForm(forms.Form):
    Oldpassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=8)
    Newpassword=forms.CharField(widget=forms.PasswordInput,max_length=8)
    Confirmpassword=forms.CharField(widget=forms.PasswordInput,max_length=8)
            
class ProductForm(forms.Form):
    class Meta():
        model=ProductTable
        fields='__all__'

   

website/views.py
from django.forms.widgets import RadioSelect
from django.shortcuts import render,redirect
from django.views.decorators.csrf import csrf_protect
from . models import ProductTable, SignUp
from website.forms import SignUpForm,LoginForm,UpdateForm,ChangePasswordForm,ProductForm
from django.contrib import messages
from django.contrib.auth import logout as logouts

# Create your views here.
def index(request):
    return render(request,'index.html')
def register(request):
    if request.method=='POST':
        form=SignUpForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            name=form.cleaned_data['Name']
            designation=form.cleaned_data['Designation']
            email=form.cleaned_data['Email']
            pic=form.cleaned_data['Pic']
            password=form.cleaned_data['Password']
            cpass=form.cleaned_data['ConfirmPassword']
            phone=form.cleaned_data['Phone']
            user=SignUp.objects.filter(Email=email).exists()
            if user:
                messages.info(request,'email already existing')
                return redirect('register/')

            elif password!=cpass:
                messages.info(request,'password mismatch')
                return redirect('register/')
            else:
                table=SignUp(Name=name,Email=email,Password=password,Pic=pic,Designation=designation,Phone=phone)
                table.save()
                messages.success(request,'REGISTARION SUCCESSFULL')
                return redirect('/')

    else:
        form=SignUpForm
    return render(request,'register.html',{'form':form})   
def login(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            user=SignUp.objects.get(Email=email)
            if not user:
                messages.info(request,'user does not exist')
                return redirect('login/')
            elif password!=user.Password:
                messages.info(request,'password is incorrect')   
                return redirect('login/') 
            else:
                messages.success(request,'LOGIN SUCCESS')
                return redirect('/home/%s' % user.id)    
    else:
        form=LoginForm()
    return render(request,'login.html',{'form':form})    

def home(request,id):
    user=SignUp.objects.get(id=id)
    return render(request,'home.html',{'user':user})  

def update(request,id):
    user=SignUp.objects.get(id=id)
    if request.method=='POST':
        form=UpdateForm(request.POST or None,request.FILES or None,instance=user)
        if form.is_valid():
            form.save()
            messages.success(request,'UPDATE SUCCESSFULL')   
            return redirect('/home/%s' % user.id) 
    else:
        form=UpdateForm(instance=user)
    return render(request,'update.html',{'form':form,'user':user})

def changePass(request,id):
    user=SignUp.objects.get(id=id)
    if request.method=='POST':
        form=ChangePasswordForm(request.POST)
        if form.is_valid():
            old=form.cleaned_data['Oldpassword']
            new=form.cleaned_data['Newpassword']
            cpass=form.cleaned_data['Confirmpassword']
            if old!=user.Password:
                messages.info(request,'Entered password is incorrect')
                return redirect('/changePass/%s' % user.id)
            elif new!=cpass:
                messages.info(request,'Password mismatch')
                return redirect('/changePass/%s' % user.id)
            else:
                user.Password=new
                user.save()
                messages.info(request,'SUCCESs')
                return redirect('/home/%s' % user.id)
    else:
        form=ChangePasswordForm()
    return render(request,'changepass.html',{'form':form,'user':user})    

def logout(request):
    logouts(request)
    messages.success(request,'SUCCESS')
    return redirect('/')

def product(request):
    pro=ProductTable.objects.all()
    return render(request,'gallery.html',{'pro':pro})
    
def productdetails(request,id):
    detail=ProductTable.objects.get(id=id)
    return render(request,'product.html',{'details':detail})

website/templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Scarica gratis GARAGE Template html/css - Web Domus Italia - Web Agency </title>
	<meta name="description" content="Scarica gratis il nostro Template HTML/CSS GARAGE. Se avete bisogno di un design per il vostro sito web GARAGE può fare per voi. Web Domus Italia">
	<meta name="author" content="Web Domus Italia">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'source/bootstrap-3.3.6-dist/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'source/font-awesome-4.5.0/css/font-awesome.css' %}"}>
	<link rel="stylesheet" type="text/css" href="{% static 'style/slider.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style/mystyle.css' %}">
</head>
<body>
<!-- Header -->
<div class="allcontain">
	<div class="header">
			<ul class="socialicon">
				<li><a href="#"><i class="fa fa-facebook"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter"></i></a></li>
				<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
				<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
			</ul>
			<ul class="givusacall">
				<li>Give us a call : +66666666 </li>
			</ul>
			<ul class="logreg">
				<li><a href="{% url 'website:login' %}">Login </a> </li>
				<li><a href="{% url 'website:register' %}"><span class="register">Register</span></a></li>
			</ul>
	</div>
	<!-- Navbar Up -->
	<nav class="topnavbar navbar-default topnav">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed toggle-costume" data-toggle="collapse" data-target="#upmenu" aria-expanded="false">
					<span class="sr-only"> Toggle navigaion</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand logo" href="#"><img src="{% static 'image/logo1.png' %}" alt="logo"></a>
			</div>	 
		</div>
		<div class="collapse navbar-collapse" id="upmenu">
			<ul class="nav navbar-nav" id="navbarontop">
				<li class="active"><a href="#">HOME</a> </li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle"	data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CATEGORIES <span class="caret"></span></a>
					<ul class="dropdown-menu dropdowncostume">
						<li><a href="#">Sport</a></li>
						<li><a href="#">Old</a></li>
						<li><a href="#">New</a></li>
					</ul>
				</li>
				<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">DEALERS <span class="caret"></span></a>
						<ul class="dropdown-menu dropdowncostume">
							<li><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="3">3</a></li>
						</ul>
				</li>
				<li>
					<a href="{% url 'website:product' %}">GALLERY</a>
 
				</li>
				<button><span class="postnewcar">POST NEW CAR</span></button>
			</ul>
		</div>
	</nav>
</div>

    {% block content %} 
    {% endblock %}    
	<!-- ______________________________________________________Bottom Menu ______________________________-->

	<div class="bottommenu">
		<div class="bottomlogo">
		<span class="dotlogo">&bullet;</span><img src="{% static 'image/collectionlogo1.png' %}" alt="logo1"><span class="dotlogo">&bullet;;</span>
		</div>
		<ul class="nav nav-tabs bottomlinks">
			<li role="presentation" ><a href="#/" role="button">ABOUT US</a></li>
			<li role="presentation"><a href="#/">CATEGORIES</a></li>
			<li role="presentation"><a href="#/">PREORDERS</a></li>
			<li role="presentation"><a href="#/">CONTACT US</a></li>
			<li role="presentation"><a href="#/">RECEIVE OUR NEWSLETTER</a></li>
		</ul>
		<p>"Lorem ipsum dolor sit amet, consectetur,  sed do eiusmod tempor incididunt <br>
			eiusmod tempor incididunt </p>
		 <img src="{% static 'image/line.png' %}" alt="line"> <br>
		 <div class="bottomsocial">
		 	<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-google-plus"></i></a>
			<a href="#"><i class="fa fa-pinterest"></i></a>
		</div>
			<div class="footer">
				<div class="copyright">
				  &copy; Copy right 2016 | <a href="#">Privacy </a>| <a href="#">Policy</a>
				</div>
				<div class="atisda">
					 Designed by <a href="http://www.webdomus.net/">Web Domus Italia - Web Agency </a> 
				</div>
			</div>
	</div>
</div>

<script type="text/javascript" src="{% static 'source/bootstrap-3.3.6-dist/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'source/js/isotope.js' %}"></script>
<script type="text/javascript" src="{% static 'source/js/myscript.js' %}"></script> 
<script type="text/javascript" src="{% static 'source/bootstrap-3.3.6-dist/js/jquery.1.11.js' % }"></script>
<script type="text/javascript" src="{% static 'source/bootstrap-3.3.6-dist/js/bootstrap.js' %}"></script>
</body>
</html>

website/templates/gallery.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for p in pro %}
    <a href="{% url 'website:productdetails' p.id %}"><img src="{{p.image.url}}" alt="" height="200px" width="200px"></a>
    {% endfor %}
    

    
</body>
</html>

website/templates/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    
    <h1>THIS IS YOUR PROFILE {{ user.Name}}</h1> <br>
    
    <img src="{{ user.Pic.url }}" alt="" style="height: 300px; width: 300px;"> <br>
    <a href="{% url 'website:update' user.id %}" style="text-decoration: none;">Update</a> <br>
    <a href="{% url 'website:changePass' user.id %}" style="text-decoration: none;">Changepass</a> <br>
    <a href="{% url 'website:logout' %}" style="text-decoration: none;">Logout</a>
</body>
</html>

website/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Hey!</strong>{{ msg }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    <hr>
    {% endfor %}
    
    <form action="" method="POST">
{% csrf_token %}
<table style="margin-top: 150px; margin-left: 750px;">

    <tr>

        <td>
            {{ form.as_table}}
        </td>
    </tr>
</table>
<input type="submit" value="Login" style="margin-left: 750px;">
    </form>
    <hr>
</body>
</html>
{% endblock %}

website/templates/product.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table>
        
        <tr>
            <td>
                {{details.Product_Name}}
            </td>
        </tr>
        <tr>
            <td>
                {{details.Model}}
            </td>
        </tr>
        <tr>
            <td>
                {{details.Price}}
            </td>
        </tr>
        <tr>
            <td>
                {{details.color}}
            </td>
        </tr>
        
    </table>
</body>
</html>

website/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
<html lang="en">
    <head>
        <script type=""></script>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>  
        <title>Document</title>
    </head>
<body>
    {% for msg in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
<strong>Hey!</strong>{{ msg }}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
{% endfor %}

    <form action="{% url 'website:register' %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<table style="margin-left: 750px; margin-top: 150px; color: crimson;">


    <tr>
        <td>
            {{ form.as_table }}
        </td>
    </tr>
</table>
<input type="submit" value="Signup" style="color: chartreuse; margin-left: 750px;">
    </form>
    


</body>
</html>
{% endblock %}

website/templates/update.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Hey!</strong>{{ msg }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% endfor %}
    
    <form action="{% url 'website:update' user.id %}" method="POST">
{% csrf_token %}  
<table>

    <tr>
        <td>
            {{form.as_table}}
        </td>
    </tr>
</table>
<input type="submit" value="Update">

    </form>
</body>
</html>